name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # include large files if any

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Fail fast if any prompt would appear
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper ""
          export GIT_TERMINAL_PROMPT=0

          # Add/replace remote with username + token + .git suffix
          git remote remove hf 2>/dev/null || true
          git remote add hf "https://samir72:${HF_TOKEN}@huggingface.co/spaces/samir72/Multi-Agent-Research-Paper-Analysis-System.git"

          # Optional: verify auth without pushing
          git ls-remote hf

          # Push main to the Space
          git push --force hf main